apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-file-server
  namespace: 06-volume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-file-server
  template:
    metadata:
      labels:
        app: simple-file-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: "worker"
      containers:
        - name: simple-file-server
          image: ghcr.io/jung-geun/simple-file-server:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: simple-file-server-config
                  key: PORT
            - name: LOG_PATH
              valueFrom:
                configMapKeyRef:
                  name: simple-file-server-config
                  key: LOG_PATH
            - name: UPLOAD_DIR
              valueFrom:
                configMapKeyRef:
                  name: simple-file-server-config
                  key: UPLOAD_DIR
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-file-server
  namespace: 06-volume
spec:
  type: NodePort
  selector:
    app: simple-file-server
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001
