[project]
name = "06-volume-configmap-secret"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
